#!/bin/sh

ssh ubuntu@ec2-13-52-186-219.us-west-1.compute.amazonaws.com <<EOF
    cd ~/perftest
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install v10.11.0
    npm install
    npm install -g nodemon pm2
    pm2 restart ecosystem.config.js
    exit
EOF


